# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ONvQ/DBD/amEpvAddelOzsP7P2Jc9mIq53+RSZNsfJUuBWG0lHFQcw==,iv:ZMYmBfHxPmq4OkISd29uPCl7TZkN58PRhgAqi9+kJGY=,tag:SbmC0dhWpQor4MiChgjKnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSXJ4dmIxaHV3QkVsRGhV
            MHNQT2k4bTM3Nmh6eXNldTdyZHBIZ3EvS0RjCkMzZlZxdnh6VkFtZEE1SHVNSjQz
            SnVoV2pOQ3o1SGYzUjg3RmQzOG5DWEEKLS0tIFpDSnliblRkcDUxejhtVjNNNXVn
            OTJKOGRTUDQ3bHR1UjRSTmd2dFdPL1UK+t1WjMLvICLCDeenFgXsV3m7C6MDQNYJ
            hZtdyjw2Z8SmFyqlCfkF1ACNzaRaUEeNXhJATnUhAfpL4HBj2GeBDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:40:24Z"
    mac: ENC[AES256_GCM,data:8Znk97w3KiQElQYlnedTiCWgdJacC+5LI7AznuzzEQRO41MfZEsfFckBCHvvUZxt3kiZs98sYmXyHuHclA49TGn+peasCI/iS98PN2rJIrAURVCJJQJ1R0Ana47E8W6luR9nX2G2brmUs+DmDbEujDsyBhE35X9L68yU4+W8WEg=,iv:a2fGAa6+axbJlZrgrSvPfo6zyUNFS54J4rE8ELsE1xE=,tag:frhgM0aeunn3vBr3PDqtAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
